using System.Collections.Generic;

namespace RoguelikeCardGame.Models
{
    public static class UpgradedCardsDatabase
    {
        // 1. DATABÁZE VŠECH VYLEPŠENÝCH KARET VE HŘE
        public static Dictionary<string, CardTemplate> UpgradedCards = new Dictionary<string, CardTemplate>
        {
            // --- ZÁKLADNÍ KARTY ---
            { "Z_Uder+", new CardTemplate("Z_Uder+", "⭐ Silný úder", "Udělí 8 zranění.", cost: 1, damage: 8) },
            { "Z_Obrana+", new CardTemplate("Z_Obrana+", "⭐ Pevný blok", "Přidá 8 bloku.", cost: 1, block: 8) },

            // ==========================================
            // 1. PALADIN (SVĚTLONOŠ) - VYLEPŠENO
            // ==========================================
            { "P_01+", new CardTemplate("P_01+", "⭐ Pravý Svatý úder", "Udělí 8 zranění. Karma +2.", cost: 1, damage: 8, karmaShift: 2) },
            { "P_02+", new CardTemplate("P_02+", "⭐ Oslňující čepel", "Udělí 10 zranění. Aplikuje 2 Zranitelnost.", cost: 1, damage: 10, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "P_03+", new CardTemplate("P_03+", "⭐ Bleskový švih", "Udělí 4 zranění dvakrát. Karma +1.", cost: 1, damage: 4, hitCount: 2, karmaShift: 1) },
            { "P_04+", new CardTemplate("P_04+", "⭐ Drtivý úder štítem", "Udělí 6 zranění a přidá 6 blok.", cost: 1, damage: 6, block: 6) },
            { "P_05+", new CardTemplate("P_05+", "⭐ Meteorický dopad", "Udělí 14 zranění. Karma -1.", cost: 2, damage: 14, karmaShift: -1) },
            { "P_06+", new CardTemplate("P_06+", "⭐ Taktický Výpad", "Udělí 7 zranění, lízni 1 kartu.", cost: 1, damage: 7, drawCards: 1) },
            { "P_07+", new CardTemplate("P_07+", "⭐ Spalující plamen", "Udělí 9 zranění. Aplikuje 3 Hoření. Karma +2.", cost: 1, damage: 9, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 3) }) },
            { "P_08+", new CardTemplate("P_08+", "⭐ Fatální rána", "Udělí 16 zranění. Karma -2.", cost: 2, damage: 16, karmaShift: -2) },
            { "P_09+", new CardTemplate("P_09+", "⭐ Svatá Odplata", "Udělí 11 zranění a přidá 4 blok.", cost: 1, damage: 11, block: 4) },
            { "P_10+", new CardTemplate("P_10+", "⭐ Poslední Soudný den", "Udělí 20 zranění. Aplikuje 3 Oslabení. Karma +2.", cost: 3, damage: 20, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "P_11+", new CardTemplate("P_11+", "⭐ Nezničitelný Svatý štít", "Přidá 9 bloku. Karma +1.", cost: 1, block: 9, karmaShift: 1) },
            { "P_12+", new CardTemplate("P_12+", "⭐ Pevnost víry", "Přidá 14 bloku. Karma +1.", cost: 2, block: 14, karmaShift: 1) },
            { "P_13+", new CardTemplate("P_13+", "⭐ Brilantní Zlatá aura", "Přidá 20 bloku. Získáš 2 Obratnosti. Karma +2.", cost: 3, block: 20, karmaShift: 2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 2) }) },
            { "P_14+", new CardTemplate("P_14+", "⭐ Štít slabých", "Přidá 11 bloku, vyléčí 4 HP.", cost: 2, block: 11, heal: 4) },
            { "P_15+", new CardTemplate("P_15+", "⭐ Karmický val", "Přidá 8 bloku za 0 energie. Karma +1.", cost: 0, block: 8, karmaShift: 1) },
            { "P_16+", new CardTemplate("P_16+", "⭐ Dokonalé Odražení", "Přidá 6 bloku a udělí 6 zranění.", cost: 1, block: 6, damage: 6) },
            { "P_17+", new CardTemplate("P_17+", "⭐ Pevnost kláštera", "Přidá 16 bloku. Karma 0.", cost: 2, block: 16) },
            { "P_18+", new CardTemplate("P_18+", "⭐ Odolnost", "Přidá 10 bloku, lízni 1 kartu.", cost: 1, block: 10, drawCards: 1) },
            { "P_19+", new CardTemplate("P_19+", "⭐ Zářící Štít úsvitu", "Přidá 12 bloku. Získáš 2 Regenerace. Karma +2.", cost: 1, block: 12, karmaShift: 2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 2) }) },
            { "P_20+", new CardTemplate("P_20+", "⭐ Nedobytná Bašta", "Přidá 26 bloku! Karma +3.", cost: 3, block: 26, karmaShift: 3) },
            { "P_21+", new CardTemplate("P_21+", "⭐ Posvěcený kov", "Přidá 8 bloku, vyléčí 5 HP.", cost: 1, block: 8, heal: 5) },
            { "P_22+", new CardTemplate("P_22+", "⭐ Bezpečné Krytí", "Přidá 8 bloku. Stojí 0.", cost: 0, block: 8) },
            { "P_23+", new CardTemplate("P_23+", "⭐ Nehybný postoj", "Přidá 11 bloku, Karma +1.", cost: 1, block: 11, karmaShift: 1) },
            { "P_24+", new CardTemplate("P_24+", "⭐ Katedrála", "Přidá 18 bloku. Karma +1.", cost: 2, block: 18, karmaShift: 1) },
            { "P_25+", new CardTemplate("P_25+", "⭐ Archandělská křídla", "Přidá 14 bloku, lízni 2 karty. Karma +2.", cost: 2, block: 14, drawCards: 2, karmaShift: 2) },
            { "P_26+", new CardTemplate("P_26+", "⭐ Hluboká Modlitba", "Vyléčí 8 HP. Karma +1.", cost: 1, heal: 8, karmaShift: 1) },
            { "P_27+", new CardTemplate("P_27+", "⭐ Zázračný dotek", "Vyléčí 12 HP. Dává cíl 3 Regenerace. Karma +2.", cost: 2, heal: 12, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 3) }) },
            { "P_28+", new CardTemplate("P_28+", "⭐ Paprsek naděje", "Vyléčí 6 HP, lízni 1 kartu.", cost: 1, heal: 6, drawCards: 1) },
            { "P_29+", new CardTemplate("P_29+", "⭐ Úplná Očista", "Vyléčí 14 HP. Karma +3.", cost: 2, heal: 14, karmaShift: 3) },
            { "P_30+", new CardTemplate("P_30+", "⭐ Božský Zázrak", "Vyléčí 28 HP! Karma +5.", cost: 3, heal: 28, karmaShift: 5) },
            { "P_31+", new CardTemplate("P_31+", "⭐ Velké požehnání", "Vyléčí 5 HP za 0 energie.", cost: 0, heal: 5) },
            { "P_32+", new CardTemplate("P_32+", "⭐ Tsunami světla", "Vyléčí 8 HP a udělí 8 zranění.", cost: 2, heal: 8, damage: 8) },
            { "P_33+", new CardTemplate("P_33+", "⭐ Pláč anděla", "Vyléčí 16 HP. Dává 4 Regenerace. Karma +2.", cost: 2, heal: 16, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 4) }) },
            { "P_34+", new CardTemplate("P_34+", "⭐ Odpuštění", "Vyléčí 8 HP. Karma +3.", cost: 1, heal: 8, karmaShift: 3) },
            { "P_35+", new CardTemplate("P_35+", "⭐ Zlatý písek", "Vyléčí 4 HP, přidá 4 blok. Stojí 0.", cost: 0, heal: 4, block: 4) },
            { "P_36+", new CardTemplate("P_36+", "⭐ Sluneční Záře", "Vyléčí 10 HP, lízni 1 kartu. Karma +1.", cost: 2, heal: 10, drawCards: 1, karmaShift: 1) },
            { "P_37+", new CardTemplate("P_37+", "⭐ Vyrovnaný klid", "Karma +6 za 0 energie.", cost: 0, karmaShift: 6) },
            { "P_38+", new CardTemplate("P_38+", "⭐ Mučednická oběť", "Aplikuje na tebe 1 Zranitelnost. Vyléčí 20 HP. Karma +2.", cost: 1, heal: 20, karmaShift: 2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 1) }) }, 
            { "P_39+", new CardTemplate("P_39+", "⭐ Fénixovo Znovuzrození", "Vyléčí 35 HP. Karma +4.", cost: 3, heal: 35, karmaShift: 4) },
            { "P_40+", new CardTemplate("P_40+", "⭐ Absolutní Sjednocení", "Vyléčí 6 HP, přidá 6 blok, lízni 2 karty.", cost: 2, heal: 6, block: 6, drawCards: 2) },
            { "P_41+", new CardTemplate("P_41+", "⭐ Osvícené poznání", "Lízni 3 karty. Karma +1.", cost: 0, drawCards: 3, karmaShift: 1) },
            { "P_42+", new CardTemplate("P_42+", "⭐ Jasné Vedení", "Lízni 4 karty. Karma +2.", cost: 1, drawCards: 4, karmaShift: 2) },
            { "P_43+", new CardTemplate("P_43+", "⭐ Spravedlivý hněv", "Udělí 6 zranění třikrát! Aplikuje 3 Oslabení. Karma +3.", cost: 3, damage: 6, hitCount: 3, karmaShift: 3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "P_44+", new CardTemplate("P_44+", "⭐ Božská smršť", "Udělí 5 zranění dvakrát. Lízni 2 karty.", cost: 2, damage: 5, hitCount: 2, drawCards: 2) },
            { "P_45+", new CardTemplate("P_45+", "⭐ Ruka Spravedlnosti", "Udělí 26 zranění. Získáš 3 Síly. Karma +2.", cost: 3, damage: 26, karmaShift: 2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "P_46+", new CardTemplate("P_46+", "⭐ Kruh vykoupení", "Přidá 20 bloku, vyléčí 14 HP. Karma +4.", cost: 3, block: 20, heal: 14, karmaShift: 4) },
            { "P_47+", new CardTemplate("P_47+", "⭐ Proslov", "Lízni 3 karty. Přidá 7 bloku.", cost: 1, drawCards: 3, block: 7) },
            { "P_48+", new CardTemplate("P_48+", "⭐ Boží Proroctví", "Lízni 5 karet! Karma 0.", cost: 2, drawCards: 5) },
            { "P_49+", new CardTemplate("P_49+", "⭐ Zásah z nebes", "Udělí 40 zranění! Karma +5.", cost: 4, damage: 40, karmaShift: 5) }, 
            { "P_50+", new CardTemplate("P_50+", "⭐ Čisté Absolutní světlo", "Vyléčí 20 HP, přidá 20 bloku, udělí 20 zranění. Získáš 3 Obratnosti. Karma +5.", cost: 5, heal: 20, block: 20, damage: 20, karmaShift: 5, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 3) }) },

            // ==========================================
            // 2. WARLOCK (STÍNOVÝ MÁG) - VYLEPŠENO
            // ==========================================
            { "W_01+", new CardTemplate("W_01+", "⭐ Průrazný Stínový šíp", "Udělí 9 zranění. Karma -1.", cost: 1, damage: 9, karmaShift: -1) },
            { "W_02+", new CardTemplate("W_02+", "⭐ Chladný Dotek smrti", "Udělí 13 zranění. Aplikuje 5 Jed. Karma -2.", cost: 1, damage: 13, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 5) }) },
            { "W_03+", new CardTemplate("W_03+", "⭐ Démonický Krvavý dráp", "Udělí 16 zranění! Aplikuje 2 Zranitelnost. Karma -3.", cost: 1, damage: 16, karmaShift: -3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "W_04+", new CardTemplate("W_04+", "⭐ Trojitý sek", "Udělí 4 zranění třikrát. Karma -1.", cost: 1, damage: 4, hitCount: 3, karmaShift: -1) },
            { "W_05+", new CardTemplate("W_05+", "⭐ Hltání duše", "Udělí 7 zranění, vyléčí 4 HP. Karma -1.", cost: 1, damage: 7, heal: 4, karmaShift: -1) },
            { "W_06+", new CardTemplate("W_06+", "⭐ Požár pekel", "Udělí 20 zranění. Aplikuje 6 Hoření. Karma -2.", cost: 2, damage: 20, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 6) }) },
            { "W_07+", new CardTemplate("W_07+", "⭐ Těžká Hniloba", "Aplikuje 7 Jed, lízni 1 kartu. Karma -2.", cost: 1, drawCards: 1, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 7) }) },
            { "W_08+", new CardTemplate("W_08+", "⭐ Kruté Bičování", "Udělí 9 zranění. Stojí 0 energie! Karma -2.", cost: 0, damage: 9, karmaShift: -2) },
            { "W_09+", new CardTemplate("W_09+", "⭐ Temný Blesk", "Udělí 26 zranění! Karma -4.", cost: 2, damage: 26, karmaShift: -4) },
            { "W_10+", new CardTemplate("W_10+", "⭐ Masivní Temná exploze", "Udělí 14 zranění. Aplikuje 3 Zranitelnost. Karma -3.", cost: 2, damage: 14, karmaShift: -3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "W_11+", new CardTemplate("W_11+", "⭐ Jedovatý polibek", "Aplikuje 8 Jed, vyléčí 6 HP. Karma -2.", cost: 2, heal: 6, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 8) }) },
            { "W_12+", new CardTemplate("W_12+", "⭐ Bouře stínů", "Udělí 7 zranění třikrát! Karma -3.", cost: 2, damage: 7, hitCount: 3, karmaShift: -3) },
            { "W_13+", new CardTemplate("W_13+", "⭐ Bestialita", "Udělí 18 zranění. Aplikuje 3 Oslabení. Karma -1.", cost: 2, damage: 18, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "W_14+", new CardTemplate("W_14+", "⭐ Záludný úder", "Udělí 11 zranění za 0 energie. Karma -3.", cost: 0, damage: 11, karmaShift: -3) },
            { "W_15+", new CardTemplate("W_15+", "⭐ Upíří Vysátí krve", "Udělí 14 zranění, vyléčí 14 HP. Karma -3.", cost: 3, damage: 14, heal: 14, karmaShift: -3) },
            { "W_16+", new CardTemplate("W_16+", "⭐ Okamžitá Nekróza", "Aplikuje 20 Jed. Karma -4.", cost: 2, karmaShift: -4, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 20) }) },
            { "W_17+", new CardTemplate("W_17+", "⭐ Zlomená duše", "Udělí 7 zranění a přidá 7 blok. Karma -1.", cost: 1, damage: 7, block: 7, karmaShift: -1) },
            { "W_18+", new CardTemplate("W_18+", "⭐ Naprosté Šílenství", "Udělí 4 zranění čtyřikrát! Získáš 2 Síly. Karma -4.", cost: 2, damage: 4, hitCount: 4, karmaShift: -4, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2) }) },
            { "W_19+", new CardTemplate("W_19+", "⭐ Agónie", "Aplikuje 6 Jed a 3 Zranitelnost. Karma -1.", cost: 1, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 6), new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "W_20+", new CardTemplate("W_20+", "⭐ Hltání světla", "Udělí 20 zranění, Karma klesne o -5!", cost: 1, damage: 20, karmaShift: -5) },
            { "W_21+", new CardTemplate("W_21+", "⭐ Výhodný Temný pakt", "Lízni 4 karty. Karma -3.", cost: 1, drawCards: 4, karmaShift: -3) },
            { "W_22+", new CardTemplate("W_22+", "⭐ Temná Krvavá oběť", "Lízni 3 karty za 0 energie. Karma -2.", cost: 0, drawCards: 3, karmaShift: -2) },
            { "W_23+", new CardTemplate("W_23+", "⭐ Pád do propasti", "Lízni 5 karet! Karma -4.", cost: 2, drawCards: 5, karmaShift: -4) },
            { "W_24+", new CardTemplate("W_24+", "⭐ Mocný Rituál", "Získáš 3 Síly. Karma -1.", cost: 0, karmaShift: -1, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "W_25+", new CardTemplate("W_25+", "⭐ Nekonečná Noční můra", "Aplikuje 5 Jed, lízni 2 karty. Karma -2.", cost: 1, drawCards: 2, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 5) }) },
            { "W_26+", new CardTemplate("W_26+", "⭐ Propast temnoty", "Získáš 3 Obratnosti. Karma -6 za 0 energie.", cost: 0, karmaShift: -6, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 3) }) },
            { "W_27+", new CardTemplate("W_27+", "⭐ Nenasytnost", "Lízni 2 karty, vyléčí 4 HP. Karma -1.", cost: 1, drawCards: 2, heal: 4, karmaShift: -1) },
            { "W_28+", new CardTemplate("W_28+", "⭐ Rouhání", "Lízni 4 karty. Aplikuje 3 Zranitelnost. Karma -2.", cost: 2, drawCards: 4, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "W_29+", new CardTemplate("W_29+", "⭐ Temná magie", "Lízni 3 karty, přidá 7 blok. Karma -2.", cost: 1, drawCards: 3, block: 7, karmaShift: -2) },
            { "W_30+", new CardTemplate("W_30+", "⭐ Lexikon mrtvých", "Lízni 7 karet!!! Karma -5.", cost: 3, drawCards: 7, karmaShift: -5) },
            { "W_31+", new CardTemplate("W_31+", "⭐ Smlouva s ďáblem", "Vyléčí 20 HP, ale Karma -5.", cost: 1, heal: 20, karmaShift: -5) },
            { "W_32+", new CardTemplate("W_32+", "⭐ Tajné vědění", "Lízni 3 karty. Stojí 0.", cost: 0, drawCards: 3) },
            { "W_33+", new CardTemplate("W_33+", "⭐ Řev smrti", "Udělí 9 zranění, lízni 3 karty. Karma -3.", cost: 1, damage: 9, drawCards: 3, karmaShift: -3) },
            { "W_34+", new CardTemplate("W_34+", "⭐ Temná forma", "Získáš 3 Síly. Karma -2.", cost: 0, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "W_35+", new CardTemplate("W_35+", "⭐ Katastrofa", "Aplikuje 8 Jed, lízni 4 karty. Karma -4.", cost: 2, drawCards: 4, karmaShift: -4, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 8) }) },
            { "W_36+", new CardTemplate("W_36+", "⭐ Zeď z kostí", "Přidá 8 bloku. Karma -1.", cost: 1, block: 8, karmaShift: -1) },
            { "W_37+", new CardTemplate("W_37+", "⭐ Pevné Brnění stínů", "Přidá 13 bloku. Karma -2.", cost: 1, block: 13, karmaShift: -2) },
            { "W_38+", new CardTemplate("W_38+", "⭐ Stínová stěna", "Přidá 16 bloku. Získáš 2 Obratnosti. Karma -3.", cost: 2, block: 16, karmaShift: -3, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 2) }) },
            { "W_39+", new CardTemplate("W_39+", "⭐ Upíří bariéra", "Přidá 11 bloku, vyléčí 4 HP. Karma -2.", cost: 1, block: 11, heal: 4, karmaShift: -2) },
            { "W_40+", new CardTemplate("W_40+", "⭐ Fázování", "Přidá 20 bloku! Karma -4.", cost: 2, block: 20, karmaShift: -4) },
            { "W_41+", new CardTemplate("W_41+", "⭐ Úplné Zastření", "Přidá 7 bloku za 0 energie.", cost: 0, block: 7) },
            { "W_42+", new CardTemplate("W_42+", "⭐ Hlas prázdnoty", "Přidá 10 bloku, lízni 2 karty. Karma -2.", cost: 1, block: 10, drawCards: 2, karmaShift: -2) },
            { "W_43+", new CardTemplate("W_43+", "⭐ Nenávist ke světlu", "Přidá 14 bloku. Aplikuje 3 Oslabení. Karma -3.", cost: 1, block: 14, karmaShift: -3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "W_44+", new CardTemplate("W_44+", "⭐ Kokon prázdnoty", "Přidá 28 bloku. Karma -5.", cost: 3, block: 28, karmaShift: -5) },
            { "W_45+", new CardTemplate("W_45+", "⭐ Hraběcí aura", "Přidá 8 bloku, vyléčí 8 HP. Karma -2.", cost: 2, block: 8, heal: 8, karmaShift: -2) },
            { "W_46+", new CardTemplate("W_46+", "⭐ Finální Apokalypsa", "Aplikuje 20 Jed. Karma -4.", cost: 3, karmaShift: -4, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 20) }) },
            { "W_47+", new CardTemplate("W_47+", "⭐ Bouře meteorů", "Udělí 12 zranění třikrát! Aplikuje 5 Hoření. Karma -5.", cost: 3, damage: 12, hitCount: 3, karmaShift: -5, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 5) }) },
            { "W_48+", new CardTemplate("W_48+", "⭐ Požírač duší", "Udělí 20 zranění, vyléčí 20 HP. Karma -4.", cost: 4, damage: 20, heal: 20, karmaShift: -4) },
            { "W_49+", new CardTemplate("W_49+", "⭐ Singularita", "Lízni 7 karet, aplikuje 7 Zranitelnost. Karma -5.", cost: 3, drawCards: 7, karmaShift: -5, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 7) }) },
            { "W_50+", new CardTemplate("W_50+", "⭐ Čistá Absolutní zkáza", "Udělí 55 zranění!!! Získáš 5 Síly. Karma -7.", cost: 5, damage: 55, karmaShift: -7, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 5) }) },

            // ==========================================
            // 3. MONK (VYROVNÁVAČ) - VYLEPŠENO
            // ==========================================
            { "M_01+", new CardTemplate("M_01+", "⭐ Osvícený Úder zenu", "Udělí 9 zranění. Karma 0.", cost: 1, damage: 9, karmaShift: 0) },
            { "M_02+", new CardTemplate("M_02+", "⭐ Bleskový Dvojitý úder", "Udělí 6 zranění dvakrát. Karma 0.", cost: 1, damage: 6, hitCount: 2, karmaShift: 0) },
            { "M_03+", new CardTemplate("M_03+", "⭐ Drtivý Kop z otočky", "Udělí 13 zranění. Aplikuje 2 Zranitelnost. Karma 0.", cost: 1, damage: 13, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "M_04+", new CardTemplate("M_04+", "⭐ Mistrovský Tlakový bod", "Aplikuje 4 Oslabení, lízni 1 kartu. Karma 0.", cost: 0, drawCards: 1, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 4) }) },
            { "M_05+", new CardTemplate("M_05+", "⭐ Zuřivá Pěst tygra", "Udělí 18 zranění. Získáš 2 Síly. Karma 0.", cost: 2, damage: 18, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2) }) },
            { "M_06+", new CardTemplate("M_06+", "⭐ Hurikán ran", "Udělí 3 zranění pětkrát! Karma 0.", cost: 2, damage: 3, hitCount: 5, karmaShift: 0) },
            { "M_07+", new CardTemplate("M_07+", "⭐ Odrazující Úder dlaní", "Udělí 8 zranění, přidá 8 blok. Karma 0.", cost: 1, damage: 8, block: 8, karmaShift: 0) },
            { "M_08+", new CardTemplate("M_08+", "⭐ Očistné Bodnutí pěstí", "Udělí 11 zranění. Karma +1.", cost: 1, damage: 11, karmaShift: 1) },
            { "M_09+", new CardTemplate("M_09+", "⭐ Drsný Tvrdý pád", "Udělí 11 zranění. Karma -1.", cost: 1, damage: 11, karmaShift: -1) },
            { "M_10+", new CardTemplate("M_10+", "⭐ Oslňující Zářivý kop", "Udělí 16 zranění. Karma +1.", cost: 2, damage: 16, karmaShift: 1) },
            { "M_11+", new CardTemplate("M_11+", "⭐ Temný Stínový kop", "Udělí 16 zranění. Karma -1.", cost: 2, damage: 16, karmaShift: -1) },
            { "M_12+", new CardTemplate("M_12+", "⭐ Nekonečná Série zenu", "Udělí 6 zranění třikrát. Karma 0.", cost: 2, damage: 6, hitCount: 3, karmaShift: 0) },
            { "M_13+", new CardTemplate("M_13+", "⭐ Drtivý Průraz", "Udělí 20 zranění. Aplikuje 3 Zranitelnost. Karma 0.", cost: 2, damage: 20, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "M_14+", new CardTemplate("M_14+", "⭐ Chyté Otevření gardu", "Aplikuje 3 Zranitelnost za 0 energie. Karma 0.", cost: 0, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "M_15+", new CardTemplate("M_15+", "⭐ Zběsilý Letící drak", "Udělí 24 zranění. Karma 0.", cost: 3, damage: 24, karmaShift: 0) },
            { "M_16+", new CardTemplate("M_16+", "⭐ Destrukce čchi", "Udělí 8 zranění, lízni 2 karty. Karma 0.", cost: 1, damage: 8, drawCards: 2, karmaShift: 0) },
            { "M_17+", new CardTemplate("M_17+", "⭐ Supí Bleskový výpad", "Udělí 9 zranění, stoji 0. Karma 0.", cost: 0, damage: 9, karmaShift: 0) },
            { "M_18+", new CardTemplate("M_18+", "⭐ Železná Těžká dlaň", "Udělí 26 zranění. Karma 0.", cost: 3, damage: 26, karmaShift: 0) },
            { "M_19+", new CardTemplate("M_19+", "⭐ Světelný Úder jeřába", "Udělí 14 zranění. Karma +1.", cost: 1, damage: 14, karmaShift: 1) },
            { "M_20+", new CardTemplate("M_20+", "⭐ Jedovatý Úder hada", "Udělí 14 zranění. Karma -1.", cost: 1, damage: 14, karmaShift: -1) },
            { "M_21+", new CardTemplate("M_21+", "⭐ Prázdná Klidná mysl", "Přidá 11 bloku. Získáš 2 Obratnosti. Karma 0.", cost: 1, block: 11, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 2) }) },
            { "M_22+", new CardTemplate("M_22+", "⭐ Pružný Ohyb rákosu", "Přidá 7 bloku, stojí 0. Karma 0.", cost: 0, block: 7, karmaShift: 0) },
            { "M_23+", new CardTemplate("M_23+", "⭐ Titanová Železná košile", "Přidá 16 bloku. Karma 0.", cost: 2, block: 16, karmaShift: 0) },
            { "M_24+", new CardTemplate("M_24+", "⭐ Silová Bariéra čchi", "Přidá 20 bloku. Karma 0.", cost: 2, block: 20, karmaShift: 0) },
            { "M_25+", new CardTemplate("M_25+", "⭐ Absolutní Vnitřní mír", "Přidá 8 bloku, vyléčí 5 HP. Karma 0.", cost: 1, block: 8, heal: 5, karmaShift: 0) },
            { "M_26+", new CardTemplate("M_26+", "⭐ Hluboká Meditace", "Lízni 3 karty. Karma 0.", cost: 1, drawCards: 3, karmaShift: 0) },
            { "M_27+", new CardTemplate("M_27+", "⭐ Tranzová Meditace", "Lízni 4 karty. Karma 0.", cost: 2, drawCards: 4, karmaShift: 0) },
            { "M_28+", new CardTemplate("M_28+", "⭐ Ostré Soustředění", "Lízni 2 karty, získáš 2 Síly. Stojí 0.", cost: 0, drawCards: 2, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2) }) },
            { "M_29+", new CardTemplate("M_29+", "⭐ Úplné Zklidnění tepu", "Vyléčí 8 HP. Karma 0.", cost: 1, heal: 8, karmaShift: 0) },
            { "M_30+", new CardTemplate("M_30+", "⭐ Živoucí Harmonie", "Vyléčí 15 HP. Karma 0.", cost: 2, heal: 15, karmaShift: 0) },
            { "M_31+", new CardTemplate("M_31+", "⭐ Reaktivní Odražení", "Přidá 11 bloku, udělí 6 zranění. Karma 0.", cost: 1, block: 11, damage: 6, karmaShift: 0) },
            { "M_32+", new CardTemplate("M_32+", "⭐ Rychlý Tok vody", "Přidá 9 bloku, lízni 2 karty. Karma 0.", cost: 1, block: 9, drawCards: 2, karmaShift: 0) },
            { "M_33+", new CardTemplate("M_33+", "⭐ Nezlomný Postoj hory", "Přidá 26 bloku! Získáš 3 Obratnosti. Karma 0.", cost: 3, block: 26, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 3) }) },
            { "M_34+", new CardTemplate("M_34+", "⭐ Zlatý Květ lotosu", "Vyléčí 7 HP, přidá 7 blok. Karma 0.", cost: 1, heal: 7, block: 7, karmaShift: 0) },
            { "M_35+", new CardTemplate("M_35+", "⭐ Absolutní Prázdnota", "Lízni 6 karet. Karma 0.", cost: 2, drawCards: 6, karmaShift: 0) },
            { "M_36+", new CardTemplate("M_36+", "⭐ Skok do Světla", "Přidá 8 bloku. Karma +2.", cost: 0, block: 8, karmaShift: 2) },
            { "M_37+", new CardTemplate("M_37+", "⭐ Skok do Stínu", "Udělí 8 zranění. Karma -2.", cost: 0, damage: 8, karmaShift: -2) },
            { "M_38+", new CardTemplate("M_38+", "⭐ Silný Přesun vah (Světlo)", "Lízni 3 karty. Karma +3.", cost: 1, drawCards: 3, karmaShift: 3) },
            { "M_39+", new CardTemplate("M_39+", "⭐ Silný Přesun vah (Temnota)", "Lízni 3 karty. Karma -3.", cost: 1, drawCards: 3, karmaShift: -3) },
            { "M_40+", new CardTemplate("M_40+", "⭐ Úplné Očištění mysli", "Vyléčí 5 HP, získáš 2 Regenerace. Karma +1.", cost: 0, heal: 5, karmaShift: 1, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 2) }) },
            { "M_41+", new CardTemplate("M_41+", "⭐ Pradávný Zlatý drak", "Udělí 32 zranění! Karma 0.", cost: 3, damage: 32, karmaShift: 0) },
            { "M_42+", new CardTemplate("M_42+", "⭐ Desetitisíc dlaní", "Udělí 4 zranění šestkrát! Karma 0.", cost: 3, damage: 4, hitCount: 6, karmaShift: 0) },
            { "M_43+", new CardTemplate("M_43+", "⭐ Boží Nesmrtelnost", "Přidá 40 bloku. Získáš 4 Obratnosti. Karma 0.", cost: 4, block: 40, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 4) }) },
            { "M_44+", new CardTemplate("M_44+", "⭐ Kosmická rovnováha", "Vyléčí 12 HP, přidá 12 blok, udělí 12 zranění. Karma 0.", cost: 3, heal: 12, block: 12, damage: 12, karmaShift: 0) },
            { "M_45+", new CardTemplate("M_45+", "⭐ Smrtící Mistrovské kombo", "Udělí 14 zranění, přidá 14 blok, lízni 3 karty. Karma 0.", cost: 3, damage: 14, block: 14, drawCards: 3, karmaShift: 0) },
            { "M_46+", new CardTemplate("M_46+", "⭐ Třetí oko (Probuzení)", "Lízni 7 karet. Získáš 3 Síly. Karma 0.", cost: 2, drawCards: 7, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "M_47+", new CardTemplate("M_47+", "⭐ Finální Úder prázdnoty", "Udělí 22 zranění za 1 energii. Karma 0.", cost: 1, damage: 22, karmaShift: 0) },
            { "M_48+", new CardTemplate("M_48+", "⭐ Božská Všudypřítomnost", "Přidá 20 bloku, lízni 4 karty. Karma 0.", cost: 3, block: 20, drawCards: 4, karmaShift: 0) },
            { "M_49+", new CardTemplate("M_49+", "⭐ Zničující Dokonalý úder", "Udělí 45 zranění! Aplikuje 4 Zranitelnost. Karma 0.", cost: 4, damage: 45, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 4) }) },
            { "M_50+", new CardTemplate("M_50+", "⭐ Čisté Osvícení", "Vyléčí 30 HP, přidá 30 bloku. Karma 0.", cost: 5, heal: 30, block: 30, karmaShift: 0) },

            // ==========================================
            // 4. BERSERKER (KRVAVÝ BERSERK) - VYLEPŠENO
            // ==========================================
            { "B_01+", new CardTemplate("B_01+", "⭐ Divoký Krvavý sek", "Udělí 11 zranění. Karma -1.", cost: 1, damage: 11, karmaShift: -1) },
            { "B_02+", new CardTemplate("B_02+", "⭐ Rychlý Dvojitý zásek", "Udělí 7 zranění dvakrát. Karma -1.", cost: 1, damage: 7, hitCount: 2, karmaShift: -1) },
            { "B_03+", new CardTemplate("B_03+", "⭐ Brutální Bezhlavý výpad", "Udělí 18 zranění. Získáš 1 Zranitelnost. Karma -2.", cost: 1, damage: 18, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 1) }) },
            { "B_04+", new CardTemplate("B_04+", "⭐ Drtivé Rozdrcení", "Udělí 24 zranění! Karma -3.", cost: 2, damage: 24, karmaShift: -3) },
            { "B_05+", new CardTemplate("B_05+", "⭐ Bestiální zuřivost", "Udělí 5 zranění třikrát. Získáš 2 Síly. Karma -2.", cost: 2, damage: 5, hitCount: 3, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2) }) },
            { "B_06+", new CardTemplate("B_06+", "⭐ Temné Obětování", "Získáš 4 Síly. (Nasimulujeme ztrátu HP). Karma -3.", cost: 1, karmaShift: -3, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 4) }) },
            { "B_07+", new CardTemplate("B_07+", "⭐ Těžká Rána naslepo", "Udělí 16 zranění. Karma -1.", cost: 1, damage: 16, karmaShift: -1) },
            { "B_08+", new CardTemplate("B_08+", "⭐ Zuřivý skus", "Udělí 8 zranění, vyléčí 4 HP. Karma -2.", cost: 1, damage: 8, heal: 4, karmaShift: -2) },
            { "B_09+", new CardTemplate("B_09+", "⭐ Úplné Proražení zbroje", "Udělí 13 zranění, aplikuje 2 Zranitelnost. Karma -1.", cost: 1, damage: 13, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "B_10+", new CardTemplate("B_10+", "⭐ Ničivý dopad", "Udělí 32 zranění! Karma -4.", cost: 3, damage: 32, karmaShift: -4) },
            { "B_11+", new CardTemplate("B_11+", "⭐ Hluboká Tržná rána", "Aplikuje 6 Jed (Krvácení), lízni 1 kartu. Karma -1.", cost: 1, drawCards: 1, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 6) }) },
            { "B_12+", new CardTemplate("B_12+", "⭐ Proražení lebky", "Udělí 20 zranění. Aplikuje 1 Zranitelnost na Tebe. Karma -2.", cost: 1, damage: 20, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 1) }) },
            { "B_13+", new CardTemplate("B_13+", "⭐ Krvavý Masakr", "Udělí 12 zranění všem. Karma -3.", cost: 2, damage: 12, karmaShift: -3) },
            { "B_14+", new CardTemplate("B_14+", "⭐ Rychlá Poprava", "Udělí 38 zranění! Karma -4.", cost: 3, damage: 38, karmaShift: -4) },
            { "B_15+", new CardTemplate("B_15+", "⭐ Čerstvá Krvavá stopa", "Udělí 9 zranění. Karma 0.", cost: 0, damage: 9, karmaShift: 0) },
            { "B_16+", new CardTemplate("B_16+", "⭐ Slepý Nekonečný hněv", "Udělí 4 zranění pětkrát! Získáš 3 Síly. Karma -4.", cost: 2, damage: 4, hitCount: 5, karmaShift: -4, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "B_17+", new CardTemplate("B_17+", "⭐ Absolutní Zlost", "Získáš 3 Síly za 0 energie! Karma -2.", cost: 0, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "B_18+", new CardTemplate("B_18+", "⭐ Krutá Odplata krve", "Udělí 16 zranění. Karma -1.", cost: 1, damage: 16, karmaShift: -1) },
            { "B_19+", new CardTemplate("B_19+", "⭐ Masivní Rozseknutí", "Udělí 28 zranění. Karma -3.", cost: 2, damage: 28, karmaShift: -3) },
            { "B_20+", new CardTemplate("B_20+", "⭐ Čisté Barbarství", "Udělí 22 zranění. Aplikuje 3 Oslabení. Karma -2.", cost: 2, damage: 22, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "B_21+", new CardTemplate("B_21+", "⭐ Drtivý Divoký švih", "Udělí 13 zranění. Karma -1.", cost: 1, damage: 13, karmaShift: -1) },
            { "B_22+", new CardTemplate("B_22+", "⭐ Ocelové Kladivo zkázy", "Udělí 36 zranění. Karma -4.", cost: 3, damage: 36, karmaShift: -4) },
            { "B_23+", new CardTemplate("B_23+", "⭐ Krutý Bolestivý sek", "Udělí 20 zranění. Karma -2.", cost: 1, damage: 20, karmaShift: -2) },
            { "B_24+", new CardTemplate("B_24+", "⭐ Nemilosrdné Rozpárání", "Udělí 10 zranění dvakrát. Karma -3.", cost: 2, damage: 10, hitCount: 2, karmaShift: -3) },
            { "B_25+", new CardTemplate("B_25+", "⭐ Krvavý Vír smrti", "Udělí 7 zranění čtyřikrát. Karma -4.", cost: 3, damage: 7, hitCount: 4, karmaShift: -4) },
            { "B_26+", new CardTemplate("B_26+", "⭐ Čistý Adrenalin", "Lízni 3 karty. Získáš 2 Síly. Stojí 0. Karma -1.", cost: 0, drawCards: 3, karmaShift: -1, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2) }) },
            { "B_27+", new CardTemplate("B_27+", "⭐ Hořící krev", "Lízni 4 karty. Získáš 3 Síly. Karma -2.", cost: 1, drawCards: 4, karmaShift: -2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "B_28+", new CardTemplate("B_28+", "⭐ Děsivý Bojový pokřik", "Lízni 2 karty, aplikuje 3 Zranitelnost (zastrašení). Karma 0.", cost: 0, drawCards: 2, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "B_29+", new CardTemplate("B_29+", "⭐ Úplné Ignorování bolesti", "Přidá 14 bloku. Získáš 2 Regenerace. Karma -1.", cost: 1, block: 14, karmaShift: -1, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 2) }) },
            { "B_30+", new CardTemplate("B_30+", "⭐ Křečovité Zatnutí zubů", "Přidá 20 bloku. Karma -2.", cost: 2, block: 20, karmaShift: -2) },
            { "B_31+", new CardTemplate("B_31+", "⭐ Odolný Krvavý štít", "Přidá 11 bloku, lízni 1 kartu. Karma -1.", cost: 1, block: 11, drawCards: 1, karmaShift: -1) },
            { "B_32+", new CardTemplate("B_32+", "⭐ Temné Šílenství", "Lízni 5 karet! Získáš 3 Síly. Karma -3.", cost: 2, drawCards: 5, karmaShift: -3, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "B_33+", new CardTemplate("B_33+", "⭐ Masivní Druhej dech", "Vyléčí 15 HP. Karma +1.", cost: 1, heal: 15, karmaShift: 1) }, 
            { "B_34+", new CardTemplate("B_34+", "⭐ Zvířecí Řev", "Lízni 3 karty. Aplikuje 3 Oslabení. Karma -2.", cost: 1, drawCards: 3, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "B_35+", new CardTemplate("B_35+", "⭐ Hroší Tlustá kůže", "Přidá 16 bloku. Karma 0.", cost: 2, block: 16, karmaShift: 0) },
            { "B_36+", new CardTemplate("B_36+", "⭐ Krvavá Zběsilost", "Lízni 3 karty. Stojí 0.", cost: 0, drawCards: 3) },
            { "B_37+", new CardTemplate("B_37+", "⭐ Absolutní Připravenost", "Lízni 4 karty, přidá 8 blok. Karma -1.", cost: 2, drawCards: 4, block: 8, karmaShift: -1) },
            { "B_38+", new CardTemplate("B_38+", "⭐ Hrdinský Poslední vzdor", "Přidá 28 bloku! Karma -2.", cost: 3, block: 28, karmaShift: -2) },
            { "B_39+", new CardTemplate("B_39+", "⭐ Ocelová Zkrvavená pěst", "Udělí 8 zranění, přidá 8 blok. Karma -1.", cost: 1, damage: 8, block: 8, karmaShift: -1) },
            { "B_40+", new CardTemplate("B_40+", "⭐ Rychlé Nabuzení", "Lízni 2 karty, vyléčí 4 HP. Karma 0.", cost: 0, drawCards: 2, heal: 4, karmaShift: 0) },
            { "B_41+", new CardTemplate("B_41+", "⭐ Ultimátní Zkáza titánů", "Udělí 45 zranění! Karma -5.", cost: 4, damage: 45, karmaShift: -5) },
            { "B_42+", new CardTemplate("B_42+", "⭐ Krvavé Ničivé tornádo", "Udělí 13 zranění třikrát! Karma -4.", cost: 3, damage: 13, hitCount: 3, karmaShift: -4) },
            { "B_43+", new CardTemplate("B_43+", "⭐ Temný Apokalyptický úder", "Udělí 65 zranění!!! Karma -6.", cost: 5, damage: 65, karmaShift: -6) },
            { "B_44+", new CardTemplate("B_44+", "⭐ Masivní Krvavá lázeň", "Udělí 16 zranění, vyléčí 16 HP. Získáš 4 Síly. Karma -4.", cost: 3, damage: 16, heal: 16, karmaShift: -4, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 4) }) },
            { "B_45+", new CardTemplate("B_45+", "⭐ Bůh Války (Nezastavitelný)", "Přidá 35 bloku, získáš 3 Síly a lízni 4 karty. Karma -3.", cost: 3, block: 35, drawCards: 4, karmaShift: -3, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "B_46+", new CardTemplate("B_46+", "⭐ Konec Světa (Ragnarok)", "Udělí 20 zranění dvakrát. Karma -5.", cost: 3, damage: 20, hitCount: 2, karmaShift: -5) },
            { "B_47+", new CardTemplate("B_47+", "⭐ Skok do temnoty", "Lízni 7 karet. Karma -5.", cost: 2, drawCards: 7, karmaShift: -5) },
            { "B_48+", new CardTemplate("B_48+", "⭐ Absolutní Totální destrukce", "Udělí 50 zranění. Karma -5.", cost: 4, damage: 50, karmaShift: -5) },
            { "B_49+", new CardTemplate("B_49+", "⭐ Déšť Krveprolití", "Udělí 10 zranění čtyřikrát! Karma -6.", cost: 4, damage: 10, hitCount: 4, karmaShift: -6) },
            { "B_50+", new CardTemplate("B_50+", "⭐ Čistý Poslední soud", "Udělí 80 zranění. Karma -7.", cost: 5, damage: 80, karmaShift: -7) },

            // ==========================================
            // 5. DRUID (OCHRÁNCE) - VYLEPŠENO
            // ==========================================
            { "D_01+", new CardTemplate("D_01+", "⭐ Pevné Šlehnutí liánou", "Udělí 6 zranění a přidá 6 blok. Karma +1.", cost: 1, damage: 6, block: 6, karmaShift: 1) },
            { "D_02+", new CardTemplate("D_02+", "⭐ Hluboké Vysátí života", "Udělí 5 zranění a vyléčí 5 HP. Karma 0.", cost: 1, damage: 5, heal: 5, karmaShift: 0) },
            { "D_03+", new CardTemplate("D_03+", "⭐ Hod balvanem", "Udělí 11 zranění. Aplikuje 2 Zranitelnost. Karma 0.", cost: 1, damage: 11, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "D_04+", new CardTemplate("D_04+", "⭐ Zběsilý Roj včel", "Udělí 3 zranění čtyřikrát. Aplikuje 4 Jed. Karma 0.", cost: 1, damage: 3, hitCount: 4, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 4) }) },
            { "D_05+", new CardTemplate("D_05+", "⭐ Smrtící Jedovatý trn", "Aplikuje 7 Jed, lízni 1 kartu. Karma -1.", cost: 1, drawCards: 1, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 7) }) },
            { "D_06+", new CardTemplate("D_06+", "⭐ Masivní Drtivý kmen", "Udělí 18 zranění. Karma 0.", cost: 2, damage: 18, karmaShift: 0) },
            { "D_07+", new CardTemplate("D_07+", "⭐ Roztrhání vlkem", "Udělí 14 zranění. Aplikuje 5 Jed. Karma -1.", cost: 1, damage: 14, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 5) }) },
            { "D_08+", new CardTemplate("D_08+", "⭐ Brutální Medvědí spár", "Udělí 16 zranění, přidá 7 blok. Karma 0.", cost: 2, damage: 16, block: 7, karmaShift: 0) },
            { "D_09+", new CardTemplate("D_09+", "⭐ Zuřivá Písečná bouře", "Udělí 8 zranění dvakrát. Karma 0.", cost: 2, damage: 8, hitCount: 2, karmaShift: 0) },
            { "D_10+", new CardTemplate("D_10+", "⭐ Velké Zemětřesení", "Udělí 20 zranění. Karma -1.", cost: 3, damage: 20, karmaShift: -1) },
            { "D_11+", new CardTemplate("D_11+", "⭐ Hluboké Kořeny", "Udělí 8 zranění. Stojí 0. Karma 0.", cost: 0, damage: 8, karmaShift: 0) },
            { "D_12+", new CardTemplate("D_12+", "⭐ Drsný Přírodní výběr", "Udělí 11 zranění, vyléčí 6 HP. Karma +1.", cost: 2, damage: 11, heal: 6, karmaShift: 1) },
            { "D_13+", new CardTemplate("D_13+", "⭐ Blesk z čistého nebe", "Udělí 24 zranění! Karma +2.", cost: 2, damage: 24, karmaShift: 2) },
            { "D_14+", new CardTemplate("D_14+", "⭐ Toxické Spory", "Udělí 5 zranění všem. Karma 0.", cost: 1, damage: 5, karmaShift: 0) },
            { "D_15+", new CardTemplate("D_15+", "⭐ Žiletkový list", "Udělí 10 zranění. Karma +1.", cost: 1, damage: 10, karmaShift: 1) },
            { "D_16+", new CardTemplate("D_16+", "⭐ Zvířecí Divoký útok", "Udělí 26 zranění. Karma -2.", cost: 3, damage: 26, karmaShift: -2) },
            { "D_17+", new CardTemplate("D_17+", "⭐ Ledový vítr", "Udělí 8 zranění, lízni 1 kartu. Karma +1.", cost: 1, damage: 8, drawCards: 1, karmaShift: 1) },
            { "D_18+", new CardTemplate("D_18+", "⭐ Krvavý Výpad šelmy", "Udělí 13 zranění. Karma 0.", cost: 1, damage: 13, karmaShift: 0) },
            { "D_19+", new CardTemplate("D_19+", "⭐ Hněv lesa (Odveta)", "Udělí 15 zranění a přidá 5 blok. Karma 0.", cost: 2, damage: 15, block: 5, karmaShift: 0) },
            { "D_20+", new CardTemplate("D_20+", "⭐ Velké Zatopení", "Udělí 16 zranění. Karma +1.", cost: 2, damage: 16, karmaShift: 1) },
            { "D_21+", new CardTemplate("D_21+", "⭐ Stará Dubová kůra", "Přidá 10 bloku. Karma +1.", cost: 1, block: 10, karmaShift: 1) },
            { "D_22+", new CardTemplate("D_22+", "⭐ Rychlá Fotosyntéza", "Vyléčí 8 HP, přidá 8 blok. Dává 3 Regenerace. Karma +2.", cost: 2, heal: 8, block: 8, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 3) }) },
            { "D_23+", new CardTemplate("D_23+", "⭐ Léčivé Bylinky", "Vyléčí 6 HP, lízni 1 kartu. Karma +1.", cost: 1, heal: 6, drawCards: 1, karmaShift: 1) },
            { "D_24+", new CardTemplate("D_24+", "⭐ Zrychlený Růst", "Získáš 2 Síly a 2 Obratnosti. Karma +1.", cost: 1, karmaShift: 1, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 2), new EffectApplication(EffectType.Dexterity, 2) }) },
            { "D_25+", new CardTemplate("D_25+", "⭐ Neprostupný porost", "Přidá 16 bloku. Karma +1.", cost: 2, block: 16, karmaShift: 1) },
            { "D_26+", new CardTemplate("D_26+", "⭐ Prastarý Léčivý pramen", "Vyléčí 12 HP. Karma +2.", cost: 1, heal: 12, karmaShift: 2) },
            { "D_27+", new CardTemplate("D_27+", "⭐ Rychlý Cyklus", "Lízni 3 karty, vyléčí 3 HP. Stojí 0. Karma 0.", cost: 0, drawCards: 3, heal: 3, karmaShift: 0) },
            { "D_28+", new CardTemplate("D_28+", "⭐ Pevná Kamenná zeď", "Přidá 20 bloku. Karma 0.", cost: 2, block: 20, karmaShift: 0) },
            { "D_29+", new CardTemplate("D_29+", "⭐ Zlatá Hojnost", "Lízni 4 karty. Karma +2.", cost: 2, drawCards: 4, karmaShift: 2) },
            { "D_30+", new CardTemplate("D_30+", "⭐ Posvátný Květ života", "Vyléčí 16 HP! Karma +3.", cost: 2, heal: 16, karmaShift: 3) },
            { "D_31+", new CardTemplate("D_31+", "⭐ Očistná Ranní rosa", "Vyléčí 5 HP za 0 energie. Karma +1.", cost: 0, heal: 5, karmaShift: 1) },
            { "D_32+", new CardTemplate("D_32+", "⭐ Lepkavá Pavučina", "Přidá 8 bloku, lízni 1 kartu. Karma 0.", cost: 1, block: 8, drawCards: 1, karmaShift: 0) },
            { "D_33+", new CardTemplate("D_33+", "⭐ Bezpečné Zátiší", "Přidá 11 bloku. Karma +2.", cost: 1, block: 11, karmaShift: 2) },
            { "D_34+", new CardTemplate("D_34+", "⭐ Hojivé Houbové spory", "Vyléčí 7 HP, přidá 4 blok. Karma 0.", cost: 1, heal: 7, block: 4, karmaShift: 0) },
            { "D_35+", new CardTemplate("D_35+", "⭐ Rychlé Zrození", "Lízni 5 karet. Karma +2.", cost: 2, drawCards: 5, karmaShift: 2) },
            { "D_36+", new CardTemplate("D_36+", "⭐ Silný Ochranný mech", "Přidá 7 bloku za 0 energie. Karma 0.", cost: 0, block: 7, karmaShift: 0) },
            { "D_37+", new CardTemplate("D_37+", "⭐ Lovcův Zvířecí instinkt", "Lízni 2 karty, Karma +1.", cost: 0, drawCards: 2, karmaShift: 1) },
            { "D_38+", new CardTemplate("D_38+", "⭐ Hluboký Medvědí spánek", "Vyléčí 20 HP, přidá 14 blok. Karma +3.", cost: 3, heal: 20, block: 14, karmaShift: 3) },
            { "D_39+", new CardTemplate("D_39+", "⭐ Zlatý Zázrak přírody", "Lízni 3 karty, vyléčí 8 HP. Karma +1.", cost: 2, drawCards: 3, heal: 8, karmaShift: 1) },
            { "D_40+", new CardTemplate("D_40+", "⭐ Živoucí Míza", "Přidá 14 bloku. Karma +1.", cost: 1, block: 14, karmaShift: 1) },
            { "D_41+", new CardTemplate("D_41+", "⭐ Prastarý Hněv lesa", "Aplikuje 15 Jed. Karma 0.", cost: 3, karmaShift: 0, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 15) }) },
            { "D_42+", new CardTemplate("D_42+", "⭐ Neprostupný Živoucí prales", "Přidá 35 bloku! Dává 6 Regenerace. Karma +3.", cost: 3, block: 35, karmaShift: 3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 6) }) },
            { "D_43+", new CardTemplate("D_43+", "⭐ Posvátný Strom života", "Vyléčí 35 HP!!! Dává 8 Regenerace. Karma +5.", cost: 4, heal: 35, karmaShift: 5, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 8) }) },
            { "D_44+", new CardTemplate("D_44+", "⭐ Zničující Sluneční erupce", "Udělí 20 zranění, vyléčí 15 HP. Karma +4.", cost: 4, damage: 20, heal: 15, karmaShift: 4) },
            { "D_45+", new CardTemplate("D_45+", "⭐ Hlasité Volání divočiny", "Lízni 7 karet. Získáš 3 Síly. Karma +2.", cost: 3, drawCards: 7, karmaShift: 2, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "D_46+", new CardTemplate("D_46+", "⭐ Apokalyptická Přírodní kat.", "Udělí 14 zranění třikrát! Karma -2.", cost: 4, damage: 14, hitCount: 3, karmaShift: -2) },
            { "D_47+", new CardTemplate("D_47+", "⭐ Absolutní Splynutí s přírodou", "Vyléčí 20 HP, přidá 20 blok, lízni 3 karty. Karma +4.", cost: 5, heal: 20, block: 20, drawCards: 3, karmaShift: 4) },
            { "D_48+", new CardTemplate("D_48+", "⭐ Dusivé Pohlcující liány", "Udělí 26 zranění, přidá 14 blok. Karma +1.", cost: 3, damage: 26, block: 14, karmaShift: 1) },
            { "D_49+", new CardTemplate("D_49+", "⭐ Zlaté Znovuzrození lesa", "Vyléčí 28 HP, lízni 4 karty. Karma +3.", cost: 4, heal: 28, drawCards: 4, karmaShift: 3) },
            { "D_50+", new CardTemplate("D_50+", "⭐ Bohyně Matka příroda", "Udělí 40 zranění, vyléčí 20 HP! Karma +5.", cost: 5, damage: 40, heal: 20, karmaShift: 5) },

            // ==========================================
            // 6. ROGUE (KARMICKÝ VRAH) - VYLEPŠENO
            // ==========================================
            { "R_01+", new CardTemplate("R_01+", "⭐ Ostrá Rychlá dýka", "Udělí 7 zranění. Karma -1.", cost: 1, damage: 7, karmaShift: -1) },
            { "R_02+", new CardTemplate("R_02+", "⭐ Rychlý Dvojitý sek", "Udělí 5 zranění dvakrát. Aplikuje 2 Zranitelnost. Karma -1.", cost: 1, damage: 5, hitCount: 2, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "R_03+", new CardTemplate("R_03+", "⭐ Krutá Zákeřná rána", "Udělí 12 zranění. Aplikuje 3 Oslabení. Karma -2.", cost: 1, damage: 12, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 3) }) },
            { "R_04+", new CardTemplate("R_04+", "⭐ Toxická Jedovatá čepel", "Aplikuje 8 Jed, lízni 1 kartu. Karma -1.", cost: 1, drawCards: 1, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Poison, 8) }) },
            { "R_05+", new CardTemplate("R_05+", "⭐ Fatální Bodnutí do zad", "Udělí 18 zranění! Karma -3.", cost: 1, damage: 18, karmaShift: -3) },
            { "R_06+", new CardTemplate("R_06+", "⭐ Sprška Vrhacích nožů", "Udělí 3 zranění třikrát. Karma 0.", cost: 1, damage: 3, hitCount: 3, karmaShift: 0) },
            { "R_07+", new CardTemplate("R_07+", "⭐ Krvavé Přepadení", "Udělí 9 zranění za 0 energie! Karma -2.", cost: 0, damage: 9, karmaShift: -2) },
            { "R_08+", new CardTemplate("R_08+", "⭐ Neviditelná čepel", "Udělí 7 zranění. Stojí 0. Karma -1.", cost: 0, damage: 7, karmaShift: -1) },
            { "R_09+", new CardTemplate("R_09+", "⭐ Hluboké Přeseknutí žil", "Udělí 11 zranění. Karma -1.", cost: 1, damage: 11, karmaShift: -1) },
            { "R_10+", new CardTemplate("R_10+", "⭐ Oslňující Zářivý klam", "Udělí 8 zranění. Karma +2.", cost: 1, damage: 8, karmaShift: 2) }, 
            { "R_11+", new CardTemplate("R_11+", "⭐ Krvavá Smrtící pirueta", "Udělí 7 zranění všem. Karma -2.", cost: 2, damage: 7, karmaShift: -2) },
            { "R_12+", new CardTemplate("R_12+", "⭐ Čisté Podříznutí", "Udělí 20 zranění. Karma -3.", cost: 2, damage: 20, karmaShift: -3) },
            { "R_13+", new CardTemplate("R_13+", "⭐ Masivní Krvavé kombo", "Udělí 9 zranění dvakrát. Karma -2.", cost: 2, damage: 9, hitCount: 2, karmaShift: -2) },
            { "R_14+", new CardTemplate("R_14+", "⭐ Temný Stínový úder", "Udělí 13 zranění, stoji 0 energie. Karma -3.", cost: 0, damage: 13, karmaShift: -3) },
            { "R_15+", new CardTemplate("R_15+", "⭐ Nemilosrdné Vykuchání", "Udělí 28 zranění! Karma -4.", cost: 2, damage: 28, karmaShift: -4) },
            { "R_16+", new CardTemplate("R_16+", "⭐ Citlivý Nervový bod", "Udělí 5 zranění, přidá 8 blok. Karma 0.", cost: 1, damage: 5, block: 8, karmaShift: 0) },
            { "R_17+", new CardTemplate("R_17+", "⭐ Zrychlený Odhoz", "Udělí 7 zranění, lízni 3 karty. Karma -1.", cost: 1, damage: 7, drawCards: 3, karmaShift: -1) },
            { "R_18+", new CardTemplate("R_18+", "⭐ Dokonalé Odvedení pozornosti", "Udělí 7 zranění. Karma +3.", cost: 1, damage: 7, karmaShift: 3) },
            { "R_19+", new CardTemplate("R_19+", "⭐ Smrtící Fantomový úder", "Udělí 14 zranění. Karma -1.", cost: 1, damage: 14, karmaShift: -1) },
            { "R_20+", new CardTemplate("R_20+", "⭐ Rychlý Záblesk dýky", "Udělí 12 zranění. Karma +1.", cost: 1, damage: 12, karmaShift: 1) },
            { "R_21+", new CardTemplate("R_21+", "⭐ Zrychlený Úhyb", "Přidá 9 bloku. Získáš 2 Obratnosti. Karma +3.", cost: 1, block: 9, karmaShift: 3, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 2) }) },
            { "R_22+", new CardTemplate("R_22+", "⭐ Hustá Kouřová clona", "Aplikuje 4 Oslabení, lízni 2 karty. Karma +2.", cost: 1, drawCards: 2, karmaShift: 2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 4) }) },
            { "R_23+", new CardTemplate("R_23+", "⭐ Pečlivá Příprava", "Lízni 4 karty! Stojí 0! Karma 0.", cost: 0, drawCards: 4, karmaShift: 0) }, 
            { "R_24+", new CardTemplate("R_24+", "⭐ Zlatá Akrobacie", "Přidá 7 bloku, lízni 3 karty. Karma +1.", cost: 1, block: 7, drawCards: 3, karmaShift: 1) },
            { "R_25+", new CardTemplate("R_25+", "⭐ Hluboké Stíny", "Přidá 14 bloku. Karma -2.", cost: 1, block: 14, karmaShift: -2) },
            { "R_26+", new CardTemplate("R_26+", "⭐ Ladné Salto vzad", "Přidá 8 bloku, Karma +4.", cost: 1, block: 8, karmaShift: 4) },
            { "R_27+", new CardTemplate("R_27+", "⭐ Rychlý Adrenalinový skok", "Lízni 3 karty. Karma +2.", cost: 1, drawCards: 3, karmaShift: 2) },
            { "R_28+", new CardTemplate("R_28+", "⭐ Kočičí Bleskové reflexy", "Přidá 20 bloku! Karma +3.", cost: 2, block: 20, karmaShift: 3) },
            { "R_29+", new CardTemplate("R_29+", "⭐ Úplné Splynutí se stínem", "Karma -6 za 0 energie.", cost: 0, karmaShift: -6) }, 
            { "R_30+", new CardTemplate("R_30+", "⭐ Čistý Výstup na světlo", "Karma +6 za 0 energie.", cost: 0, karmaShift: 6) }, 
            { "R_31+", new CardTemplate("R_31+", "⭐ Ostré Soustředění", "Lízni 3 karty, vyléčí 4 HP. Karma 0.", cost: 1, drawCards: 3, heal: 4, karmaShift: 0) },
            { "R_32+", new CardTemplate("R_32+", "⭐ Bezpečný Útěk", "Přidá 16 bloku. Karma +2.", cost: 2, block: 16, karmaShift: 2) },
            { "R_33+", new CardTemplate("R_33+", "⭐ Ruská ruleta (Hra se smrtí)", "Lízni 6 karet. Karma -3.", cost: 1, drawCards: 6, karmaShift: -3) },
            { "R_34+", new CardTemplate("R_34+", "⭐ Zlaté Přežití", "Vyléčí 8 HP, přidá 8 blok. Karma +1.", cost: 1, heal: 8, block: 8, karmaShift: 1) },
            { "R_35+", new CardTemplate("R_35+", "⭐ Rychlý Falešný krok", "Přidá 7 bloku za 0 energie. Karma -1.", cost: 0, block: 7, karmaShift: -1) },
            { "R_36+", new CardTemplate("R_36+", "⭐ Mistrovské Ošálení", "Lízni 2 karty, přidá 5 blok. Stojí 0.", cost: 0, drawCards: 2, block: 5, karmaShift: 0) },
            { "R_37+", new CardTemplate("R_37+", "⭐ Bohaté Zásoby", "Vyléčí 12 HP. Karma +2.", cost: 1, heal: 12, karmaShift: 2) },
            { "R_38+", new CardTemplate("R_38+", "⭐ Skrytý Mistr úniků", "Přidá 28 bloku! Karma +4.", cost: 3, block: 28, karmaShift: 4) },
            { "R_39+", new CardTemplate("R_39+", "⭐ Jasná Předtucha", "Lízni 3 karty, přidá 8 blok. Karma +1.", cost: 1, drawCards: 3, block: 8, karmaShift: 1) },
            { "R_40+", new CardTemplate("R_40+", "⭐ Čisté Odhalení slabiny", "Lízni 4 karty. Karma +2.", cost: 2, drawCards: 4, karmaShift: 2) },
            { "R_41+", new CardTemplate("R_41+", "⭐ Krvavý Tanec stínů", "Udělí 7 zranění pětkrát! Aplikuje 4 Zranitelnost. Karma -5.", cost: 3, damage: 7, hitCount: 5, karmaShift: -5, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 4) }) },
            { "R_42+", new CardTemplate("R_42+", "⭐ Zlaté Nekonečné kombo", "Lízni 7 karet! Získáš 3 Síly. Karma 0.", cost: 2, drawCards: 7, karmaShift: 0, selfEffects: new List<EffectApplication> { new EffectApplication(EffectType.Strength, 3) }) },
            { "R_43+", new CardTemplate("R_43+", "⭐ Tichý Atentát", "Udělí 55 zranění! Karma -4.", cost: 3, damage: 55, karmaShift: -4) },
            { "R_44+", new CardTemplate("R_44+", "⭐ Nehmotný Přízrak", "Přidá 42 bloku!!! Karma +5.", cost: 3, block: 42, karmaShift: 5) },
            { "R_45+", new CardTemplate("R_45+", "⭐ Smrtící Krvavá stopa", "Udělí 20 zranění dvakrát, lízni 3 karty. Karma -3.", cost: 3, damage: 20, hitCount: 2, drawCards: 3, karmaShift: -3) },
            { "R_46+", new CardTemplate("R_46+", "⭐ Zlatý Dokonalý plán", "Lízni 8 karet! Karma +2.", cost: 3, drawCards: 8, karmaShift: 2) },
            { "R_47+", new CardTemplate("R_47+", "⭐ Zářící Skrytý drak", "Udělí 35 zranění za 1 energii. Karma -2.", cost: 1, damage: 35, karmaShift: -2) },
            { "R_48+", new CardTemplate("R_48+", "⭐ Absolutní Očištění krve", "Vyléčí 30 HP. Karma +5.", cost: 3, heal: 30, karmaShift: 5) },
            { "R_49+", new CardTemplate("R_49+", "⭐ Železná Bouře dýk", "Udělí 4 zranění desetkrát!!! Karma -6.", cost: 4, damage: 4, hitCount: 10, karmaShift: -6) },
            { "R_50+", new CardTemplate("R_50+", "⭐ Chladný Dotek smrtky", "Udělí 85 zranění. Karma -8.", cost: 4, damage: 85, karmaShift: -8) },

            // ==========================================
            // 7. BARD (SUPPORT) - VYLEPŠENO
            // ==========================================
            { "Bd_01+", new CardTemplate("Bd_01+", "⭐ Průrazný Falešný tón", "Udělí 6 zranění. Aplikuje 2 Oslabení. Karma -1.", cost: 1, damage: 6, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 2) }) },
            { "Bd_02+", new CardTemplate("Bd_02+", "⭐ Dokonalý Ostrý akord", "Udělí 8 zranění. Aplikuje 2 Zranitelnost. Karma +1.", cost: 1, damage: 8, karmaShift: 1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 2) }) },
            { "Bd_03+", new CardTemplate("Bd_03+", "⭐ Silný Rytmický úder", "Udělí 4 zranění dvakrát. Karma 0.", cost: 1, damage: 4, hitCount: 2, karmaShift: 0) },
            { "Bd_04+", new CardTemplate("Bd_04+", "⭐ Hlasitá Rušivá píseň", "Udělí 6 zranění, lízni 2 karty. Karma -1.", cost: 1, damage: 6, drawCards: 2, karmaShift: -1) },
            { "Bd_05+", new CardTemplate("Bd_05+", "⭐ Slavný Bojový marš", "Udělí 9 zranění, přidá 5 blok. Karma +1.", cost: 1, damage: 9, block: 5, karmaShift: 1) },
            { "Bd_06+", new CardTemplate("Bd_06+", "⭐ Krutý Výsměch", "Udělí 12 zranění. Karma -2.", cost: 1, damage: 12, karmaShift: -2) },
            { "Bd_07+", new CardTemplate("Bd_07+", "⭐ Masivní Crescendo", "Udělí 16 zranění. Karma +2.", cost: 2, damage: 16, karmaShift: 2) },
            { "Bd_08+", new CardTemplate("Bd_08+", "⭐ Rychlé Bodnutí dýkou", "Udělí 9 zranění. Stojí 0. Karma -1.", cost: 0, damage: 9, karmaShift: -1) },
            { "Bd_09+", new CardTemplate("Bd_09+", "⭐ Zvukový ryk", "Udělí 7 zranění všem. Karma -2.", cost: 2, damage: 7, karmaShift: -2) },
            { "Bd_10+", new CardTemplate("Bd_10+", "⭐ Bolestivá Disonance", "Udělí 14 zranění. Karma -3.", cost: 1, damage: 14, karmaShift: -3) },
            { "Bd_11+", new CardTemplate("Bd_11+", "⭐ Prastarý Hrdinský epos", "Udělí 11 zranění, vyléčí 4 HP. Karma +1.", cost: 2, damage: 11, heal: 4, karmaShift: 1) },
            { "Bd_12+", new CardTemplate("Bd_12+", "⭐ Nekonečná Ozvena", "Udělí 4 zranění třikrát. Karma 0.", cost: 2, damage: 4, hitCount: 3, karmaShift: 0) },
            { "Bd_13+", new CardTemplate("Bd_13+", "⭐ Těžká Rána loutnou", "Udělí 20 zranění. Karma -1.", cost: 2, damage: 20, karmaShift: -1) },
            { "Bd_14+", new CardTemplate("Bd_14+", "⭐ Rychlé Sólo na bubny", "Udělí 8 zranění za 0 energie. Karma 0.", cost: 0, damage: 8, karmaShift: 0) },
            { "Bd_15+", new CardTemplate("Bd_15+", "⭐ Smrtící Závěrečný tón", "Udělí 28 zranění. Karma -2.", cost: 3, damage: 28, karmaShift: -2) },
            { "Bd_16+", new CardTemplate("Bd_16+", "⭐ Zářivá Píseň naděje", "Vyléčí 6 HP, přidá 6 blok. Dává 3 Regenerace. Karma +3.", cost: 1, heal: 6, block: 6, karmaShift: 3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 3) }) },
            { "Bd_17+", new CardTemplate("Bd_17+", "⭐ Konejšivá melodie", "Přidá 11 bloku. Karma +2.", cost: 1, block: 11, karmaShift: 2) },
            { "Bd_18+", new CardTemplate("Bd_18+", "⭐ Zlatá Hymna ochrany", "Přidá 20 bloku. Dává 3 Obratnosti. Karma +3.", cost: 2, block: 20, karmaShift: 3, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Dexterity, 3) }) },
            { "Bd_19+", new CardTemplate("Bd_19+", "⭐ Čistá Píseň světla", "Vyléčí 12 HP. Karma +2.", cost: 1, heal: 12, karmaShift: 2) },
            { "Bd_20+", new CardTemplate("Bd_20+", "⭐ Velké Povzbuzení", "Lízni 3 karty. Karma +1.", cost: 1, drawCards: 3, karmaShift: 1) },
            { "Bd_21+", new CardTemplate("Bd_21+", "⭐ Tichá Ukolébavka", "Přidá 14 bloku, lízni 2 karty. Karma +2.", cost: 2, block: 14, drawCards: 2, karmaShift: 2) },
            { "Bd_22+", new CardTemplate("Bd_22+", "⭐ Andělský Léčivý sbor", "Vyléčí 18 HP. Karma +3.", cost: 2, heal: 18, karmaShift: 3) },
            { "Bd_23+", new CardTemplate("Bd_23+", "⭐ Múzina Inspirace", "Lízni 4 karty. Karma 0.", cost: 1, drawCards: 4, karmaShift: 0) },
            { "Bd_24+", new CardTemplate("Bd_24+", "⭐ Virtuózní akordy", "Přidá 8 bloku, lízni 3 karty. Karma +1.", cost: 1, block: 8, drawCards: 3, karmaShift: 1) },
            { "Bd_25+", new CardTemplate("Bd_25+", "⭐ Neprostupný Štít z hudby", "Přidá 28 bloku! Karma +4.", cost: 3, block: 28, karmaShift: 4) },
            { "Bd_26+", new CardTemplate("Bd_26+", "⭐ Upřímná serenáda", "Vyléčí 8 HP za 0 energie. Karma +1.", cost: 0, heal: 8, karmaShift: 1) },
            { "Bd_27+", new CardTemplate("Bd_27+", "⭐ Šťastná zpráva", "Vyléčí 5 HP, přidá 8 blok. Karma +2.", cost: 1, heal: 5, block: 8, karmaShift: 2) },
            { "Bd_28+", new CardTemplate("Bd_28+", "⭐ Věčná Melodie života", "Vyléčí 22 HP! Karma +4.", cost: 3, heal: 22, karmaShift: 4) },
            { "Bd_29+", new CardTemplate("Bd_29+", "⭐ Zlatá pauza", "Přidá 7 bloku. Stojí 0. Karma 0.", cost: 0, block: 7, karmaShift: 0) },
            { "Bd_30+", new CardTemplate("Bd_30+", "⭐ Velkolepý Sborový zpěv", "Vyléčí 11 HP, přidá 11 blok. Karma +3.", cost: 2, heal: 11, block: 11, karmaShift: 3) },
            { "Bd_31+", new CardTemplate("Bd_31+", "⭐ Přítomnost múzy", "Lízni 3 karty, vyléčí 4 HP. Karma +1.", cost: 1, drawCards: 3, heal: 4, karmaShift: 1) },
            { "Bd_32+", new CardTemplate("Bd_32+", "⭐ Ocelový rytmus", "Přidá 16 bloku. Karma +1.", cost: 1, block: 16, karmaShift: 1) },
            { "Bd_33+", new CardTemplate("Bd_33+", "⭐ Rychlá Balada o štítu", "Přidá 12 bloku za 0 energie! Karma +2.", cost: 0, block: 12, karmaShift: 2) },
            { "Bd_34+", new CardTemplate("Bd_34+", "⭐ Fénixova Píseň znovuzrození", "Vyléčí 14 HP, lízni 2 karty. Karma +3.", cost: 2, heal: 14, drawCards: 2, karmaShift: 3) },
            { "Bd_35+", new CardTemplate("Bd_35+", "⭐ Absolutní Harmonie duší", "Vyléčí 9 HP, přidá 9 blok. Karma +2.", cost: 1, heal: 9, block: 9, karmaShift: 2) },
            { "Bd_36+", new CardTemplate("Bd_36+", "⭐ Píseň absolutního zmaru", "Udělí 5 zranění. Karma -6! (Pro pomoc Warlockovi).", cost: 1, damage: 5, karmaShift: -6) },
            { "Bd_37+", new CardTemplate("Bd_37+", "⭐ Hluboký Zpěv zoufalství", "Lízni 4 karty. Karma -3.", cost: 1, drawCards: 4, karmaShift: -3) },
            { "Bd_38+", new CardTemplate("Bd_38+", "⭐ Posvátný chorál", "Přidá 8 bloku. Karma +7! (Pro pomoc Paladinovi).", cost: 1, block: 8, karmaShift: 7) },
            { "Bd_39+", new CardTemplate("Bd_39+", "⭐ Propast do temnot", "Karma -8 za 0 energie.", cost: 0, karmaShift: -8) },
            { "Bd_40+", new CardTemplate("Bd_40+", "⭐ Schody ke světlu", "Karma +8 za 0 energie.", cost: 0, karmaShift: 8) },
            { "Bd_41+", new CardTemplate("Bd_41+", "⭐ Tragická melodie", "Vyléčí 7 HP. Karma -2.", cost: 1, heal: 7, karmaShift: -2) },
            { "Bd_42+", new CardTemplate("Bd_42+", "⭐ Euforická melodie", "Vyléčí 7 HP. Karma +2.", cost: 1, heal: 7, karmaShift: 2) },
            { "Bd_43+", new CardTemplate("Bd_43+", "⭐ Hrozné Rozladění", "Udělí 9 zranění. Karma -3.", cost: 1, damage: 9, karmaShift: -3) },
            { "Bd_44+", new CardTemplate("Bd_44+", "⭐ Božské naladění", "Lízni 4 karty. Karma +3.", cost: 2, drawCards: 4, karmaShift: 3) },
            { "Bd_45+", new CardTemplate("Bd_45+", "⭐ Vyvážený Karmický obrat", "Udělí 4 zranění, přidá 4 blok. Karma 0.", cost: 0, damage: 4, block: 4, karmaShift: 0) },
            { "Bd_46+", new CardTemplate("Bd_46+", "⭐ Božská Óda na radost", "Vyléčí 35 HP! Dává 15 Regenerace. Karma +6.", cost: 4, heal: 35, karmaShift: 6, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Regen, 15) }) },
            { "Bd_47+", new CardTemplate("Bd_47+", "⭐ Temné Requiem", "Udělí 40 zranění! Aplikuje 7 Oslabení. Karma -6.", cost: 4, damage: 40, karmaShift: -6, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Weak, 7) }) },
            { "Bd_48+", new CardTemplate("Bd_48+", "⭐ Titánská Symfonie štítů", "Přidá 55 bloku!!! Karma +4.", cost: 4, block: 55, karmaShift: 4) },
            { "Bd_49+", new CardTemplate("Bd_49+", "⭐ Historické Mistrovské dílo", "Vyléčí 20 HP, přidá 20 blok, lízni 4 karty. Karma +5.", cost: 5, heal: 20, block: 20, drawCards: 4, karmaShift: 5) },
            { "Bd_50+", new CardTemplate("Bd_50+", "⭐ Nekonečný Poslední přídavek", "Lízni 9 karet! Karma 0.", cost: 3, drawCards: 9, karmaShift: 0) },

            // ==========================================
            // 8. PYROMANCER (PYROMANT) - VYLEPŠENO
            // ==========================================
            { "Py_01+", new CardTemplate("Py_01+", "⭐ Masivní Ohnivá koule", "Udělí 16 zranění. Aplikuje 4 Hoření. Karma -1.", cost: 2, damage: 16, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 4) }) },
            { "Py_02+", new CardTemplate("Py_02+", "⭐ Ostrá Jiskra", "Udělí 7 zranění za 0 energie. Karma 0.", cost: 0, damage: 7, karmaShift: 0) },
            { "Py_03+", new CardTemplate("Py_03+", "⭐ Horký Zápal", "Aplikuje 7 Hoření. Karma -1.", cost: 1, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 7) }) },
            { "Py_04+", new CardTemplate("Py_04+", "⭐ Dvojitý Plamínek", "Udělí 5 zranění dvakrát. Karma 0.", cost: 1, damage: 5, hitCount: 2, karmaShift: 0) },
            { "Py_05+", new CardTemplate("Py_05+", "⭐ Smrtící Ohnivý bič", "Udělí 13 zranění. Aplikuje 3 Zranitelnost. Karma -2.", cost: 1, damage: 13, karmaShift: -2, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Vulnerable, 3) }) },
            { "Py_06+", new CardTemplate("Py_06+", "⭐ Rychlé Vzplanutí", "Udělí 8 zranění, lízni 2 karty. Karma -1.", cost: 1, damage: 8, drawCards: 2, karmaShift: -1) },
            { "Py_07+", new CardTemplate("Py_07+", "⭐ Brutální Sežehnutí", "Udělí 19 zranění. Karma -2.", cost: 2, damage: 19, karmaShift: -2) },
            { "Py_08+", new CardTemplate("Py_08+", "⭐ Ničivý Ohnivý proud", "Udělí 6 zranění třikrát. Karma -1.", cost: 2, damage: 6, hitCount: 3, karmaShift: -1) },
            { "Py_09+", new CardTemplate("Py_09+", "⭐ Gigantická Exploze", "Udělí 24 zranění! Karma -3.", cost: 2, damage: 24, karmaShift: -3) },
            { "Py_10+", new CardTemplate("Py_10+", "⭐ Pekelný Dračí dech", "Udělí 15 zranění všem. Karma -2.", cost: 2, damage: 15, karmaShift: -2) },
            { "Py_11+", new CardTemplate("Py_11+", "⭐ Horké Spáleniště", "Udělí 9 zranění, přidá 6 blok. Karma -1.", cost: 1, damage: 9, block: 6, karmaShift: -1) },
            { "Py_12+", new CardTemplate("Py_12+", "⭐ Dusivý Popel", "Udělí 8 zranění. Stojí 0. Karma -1.", cost: 0, damage: 8, karmaShift: -1) },
            { "Py_13+", new CardTemplate("Py_13+", "⭐ Apokalyptická Vulkanická rána", "Udělí 28 zranění! Karma -4.", cost: 3, damage: 28, karmaShift: -4) },
            { "Py_14+", new CardTemplate("Py_14+", "⭐ Těžký Ohnivý déšť", "Udělí 9 zranění dvakrát. Karma -2.", cost: 2, damage: 9, hitCount: 2, karmaShift: -2) },
            { "Py_15+", new CardTemplate("Py_15+", "⭐ Smrtící Tepelný šok", "Udělí 20 zranění. Karma -2.", cost: 2, damage: 20, karmaShift: -2) },
            { "Py_16+", new CardTemplate("Py_16+", "⭐ Úplné Roztavení", "Udělí 12 zranění, lízni 3 karty. Karma -3.", cost: 2, damage: 12, drawCards: 3, karmaShift: -3) },
            { "Py_17+", new CardTemplate("Py_17+", "⭐ Spalující Žhavé uhlíky", "Udělí 3 zranění čtyřikrát. Karma -1.", cost: 1, damage: 3, hitCount: 4, karmaShift: -1) },
            { "Py_18+", new CardTemplate("Py_18+", "⭐ Nezkrotný Výbuch hněvu", "Udělí 16 zranění. Karma -3.", cost: 1, damage: 16, karmaShift: -3) },
            { "Py_19+", new CardTemplate("Py_19+", "⭐ Zničující Pekelný šleh", "Udělí 33 zranění. Karma -4.", cost: 3, damage: 33, karmaShift: -4) },
            { "Py_20+", new CardTemplate("Py_20+", "⭐ Čisté Zpopelnění", "Udělí 40 zranění! Karma -5.", cost: 4, damage: 40, karmaShift: -5) },
            { "Py_21+", new CardTemplate("Py_21+", "⭐ Pevný Ohnivý štít", "Přidá 11 bloku. Aplikuje 5 Hoření. Karma -1.", cost: 1, block: 11, karmaShift: -1, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 5) }) },
            { "Py_22+", new CardTemplate("Py_22+", "⭐ Neprostupná Zeď plamenů", "Přidá 16 bloku. Karma -2.", cost: 2, block: 16, karmaShift: -2) },
            { "Py_23+", new CardTemplate("Py_23+", "⭐ Okamžitá Kauterizace", "Vyléčí 9 HP, ale Karma -2.", cost: 1, heal: 9, karmaShift: -2) }, 
            { "Py_24+", new CardTemplate("Py_24+", "⭐ Rychlé Rozdmýchání", "Lízni 3 karty. Karma -1.", cost: 1, drawCards: 3, karmaShift: -1) },
            { "Py_25+", new CardTemplate("Py_25+", "⭐ Hltavé Krmení ohně", "Lízni 4 karty! Karma -2.", cost: 1, drawCards: 4, karmaShift: -2) },
            { "Py_26+", new CardTemplate("Py_26+", "⭐ Bezpečné Teplo domova", "Vyléčí 6 HP, přidá 6 blok. Karma +1.", cost: 1, heal: 6, block: 6, karmaShift: 1) }, 
            { "Py_27+", new CardTemplate("Py_27+", "⭐ Hustý Dým", "Přidá 9 bloku za 0 energie. Karma -1.", cost: 0, block: 9, karmaShift: -1) },
            { "Py_28+", new CardTemplate("Py_28+", "⭐ Rychlé Uhašení", "Přidá 14 bloku. Karma 0.", cost: 1, block: 14, karmaShift: 0) },
            { "Py_29+", new CardTemplate("Py_29+", "⭐ Čistý Přísun kyslíku", "Lízni 3 karty. Stojí 0. Karma -1.", cost: 0, drawCards: 3, karmaShift: -1) },
            { "Py_30+", new CardTemplate("Py_30+", "⭐ Extrémní Žár", "Udělí 10 zranění, přidá 10 blok. Karma -2.", cost: 2, damage: 10, block: 10, karmaShift: -2) },
            { "Py_31+", new CardTemplate("Py_31+", "⭐ Vroucí Magma", "Přidá 20 bloku. Karma -3.", cost: 2, block: 20, karmaShift: -3) },
            { "Py_32+", new CardTemplate("Py_32+", "⭐ Ostré Soustředění plamene", "Lízni 2 karty, Karma -2.", cost: 0, drawCards: 2, karmaShift: -2) },
            { "Py_33+", new CardTemplate("Py_33+", "⭐ Zlaté Fénixovo pírko", "Vyléčí 22 HP! Karma +2.", cost: 3, heal: 22, karmaShift: 2) },
            { "Py_34+", new CardTemplate("Py_34+", "⭐ Vroucí Hořící krev", "Vyléčí 8 HP, lízni 2 karty. Karma -1.", cost: 1, heal: 8, drawCards: 2, karmaShift: -1) },
            { "Py_35+", new CardTemplate("Py_35+", "⭐ Úplné Zatmění", "Karma -6 za 0 energie. (Pro zesílení relikvie)", cost: 0, karmaShift: -6) },
            { "Py_36+", new CardTemplate("Py_36+", "⭐ Oslňující Světlice", "Lízni 3 karty, Karma +2.", cost: 1, drawCards: 3, karmaShift: 2) },
            { "Py_37+", new CardTemplate("Py_37+", "⭐ Kamenný Lávový štít", "Přidá 28 bloku! Karma -4.", cost: 3, block: 28, karmaShift: -4) },
            { "Py_38+", new CardTemplate("Py_38+", "⭐ Běsnící Sopka", "Udělí 15 zranění, přidá 15 blok. Karma -3.", cost: 3, damage: 15, block: 15, karmaShift: -3) },
            { "Py_39+", new CardTemplate("Py_39+", "⭐ Zběsilé Zrychlené hoření", "Lízni 6 karet. Karma -3.", cost: 2, drawCards: 6, karmaShift: -3) },
            { "Py_40+", new CardTemplate("Py_40+", "⭐ Hřejivá Plamenná aura", "Přidá 8 bloku. Stojí 0. Karma 0.", cost: 0, block: 8, karmaShift: 0) },
            { "Py_41+", new CardTemplate("Py_41+", "⭐ Ultimátní Inferno", "Udělí 14 zranění třikrát!!! Aplikuje 15 Hoření. Karma -4.", cost: 3, damage: 14, hitCount: 3, karmaShift: -4, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 15) }) },
            { "Py_42+", new CardTemplate("Py_42+", "⭐ Destruktivní Supernova", "Udělí 55 zranění všem! Aplikuje 8 Hoření. Karma -6.", cost: 4, damage: 55, karmaShift: -6, targetEffects: new List<EffectApplication> { new EffectApplication(EffectType.Flame, 8) }) },
            { "Py_43+", new CardTemplate("Py_43+", "⭐ Obří Meteor", "Udělí 65 zranění! Karma -5.", cost: 4, damage: 65, karmaShift: -5) },
            { "Py_44+", new CardTemplate("Py_44+", "⭐ Nekonečná Ohnivá bouře", "Udělí 7 zranění osmkrát!!! Karma -7.", cost: 5, damage: 7, hitCount: 8, karmaShift: -7) },
            { "Py_45+", new CardTemplate("Py_45+", "⭐ Absolutní Spálení na prach", "Udělí 45 zranění, lízni 4 karty. Karma -4.", cost: 4, damage: 45, drawCards: 4, karmaShift: -4) },
            { "Py_46+", new CardTemplate("Py_46+", "⭐ Božská Sluneční záře", "Vyléčí 28 HP, přidá 28 blok! Karma +5.", cost: 4, heal: 28, block: 28, karmaShift: 5) },
            { "Py_47+", new CardTemplate("Py_47+", "⭐ Tepající Srdce sopky", "Lízni 8 karet! Karma -4.", cost: 3, drawCards: 8, karmaShift: -4) },
            { "Py_48+", new CardTemplate("Py_48+", "⭐ Smrtící Plamenný kruh", "Přidá 40 bloku, udělí 20 zranění. Karma -3.", cost: 4, block: 40, damage: 20, karmaShift: -3) },
            { "Py_49+", new CardTemplate("Py_49+", "⭐ Pravý Armagedon", "Udělí 80 zranění! Karma -8.", cost: 5, damage: 80, karmaShift: -8) },
            { "Py_50+", new CardTemplate("Py_50+", "⭐ Apokalyptický Konečný plamen", "Udělí 140 zranění!!! Karma -10.", cost: 5, damage: 140, karmaShift: -10) }
        };
    }
}